config/routes.rb
Rails.application.routes.draw do
  root to: 'subeddits#index'
  resources :subeddits do 
    resources :posts
  end

  namespace 'admin' do
    resources :subeddits
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :subeddit
end

app/models/subeddit.rb
class Subeddit < ApplicationRecord
  has_many :posts
end

app/models/subreddit.rb
class Subreddit < ApplicationRecord
  has_many :posts
end

app/controllers/admin/subeddits_controller.rb
class Admin::SubedditsController < ApplicationController
  def index
    @subeddits = Subeddit.all
  end

  def destroy
    @subeddit = Subeddit.find(params[:id])
    @subeddit.destroy

    redirect_to :subeddits
  end
end

app/controllers/admin/subreddits_controller.rb
class Admin::SubredditsController < ApplicationController
  def index
    @subreddits = Subreddit.all
  end
  def create
    @subreddit = Subreddit.new(subreddit_params)
    if @subreddit.save!
      redirect_to subreddits_url
    end
  end
  def destroy
    @subreddit = Subreddit.find(params[:id])
    @subreddit.destroy
    redirect_to subreddits_url
  end
  private
  def subreddit_params
    params.require(:subreddit).permit(:title, :description, :image)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @subeddit = Subeddit.find(params[:subeddit_id])
  end


  def create
    @subeddit = Subeddit.find(params[:subeddit_id])

    if @subeddit.posts.create!(allowed_params)
      redirect_to  subeddit_posts_url(@subeddit)
    else
      
    end

  end

  private
  def allowed_params
    params.require(:post).permit(:name, :content)
  end
end

app/controllers/subeddits_controller.rb
class SubedditsController < ApplicationController

  def index
    @subeddits = Subeddit.all
  end

end

app/controllers/subreddits_controller.rb
class SubredditsController < ApplicationController
  def index
    # pass list of subreddits to view
    @subreddits = Subreddit.all
  end
end

app/helpers/admin/subeddits_helper.rb
module Admin::SubedditsHelper
end

app/helpers/admin/subreddits_helper.rb
module Admin::SubredditsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/subeddits_helper.rb
module SubedditsHelper
end

app/helpers/subreddits_helper.rb
module SubredditsHelper
end

app/helpers/threads_helper.rb
module ThreadsHelper
end

app/views/admin/subeddits/index.html.erb
<h1>Yoooo</h1>

<% @subeddits.each do |subeddit| %>
  <div>
    <h2><%= link_to subeddit.name, subeddit_posts_path(subeddit)  %> </h2>
    <%= button_to "delete", admin_subeddit_url(subeddit), method: :delete %>
    <img style="max-width: 400px; height: auto" src=<%= subeddit.image %> ></img>
  </div>
<% end %>

app/views/admin/subreddits/index.html.erb
<h1> Subreddits </h1>
<h3> Admin </h3>
<%= form_for :subreddit , url: admin_subreddits_url do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.label :image %>
  <%= f.text_field :image %>
  <%= f.submit "Create" %>
<% end %>

<% @subreddits.each do |subreddit| %>
  <h2><%= link_to subreddit.title, subreddit_posts_url(subreddit) %> </h2>
  <%= button_to "Delete", admin_subreddit_url(subreddit), method: :delete %>
  <img src=<%= subreddit.image %> style="height: 150px" />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eddit</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<h1> <%= @subeddit.name %> </h1>
<h2> <%= @subeddit.description %> </h2>

<%= form_for :post , url: subeddit_posts_url(@subeddit) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.submit "Post a post" %>
<% end %>

<% @subeddit.posts.each do |post| %>
  <h3> <%= post.name %> </h3>
  <p> <%= post.content %> </p>
<% end %>

app/views/subeddits/index.html.erb
<h1>Yoooo</h1>

<% @subeddits.each do |subeddit| %>
  <div>
    <h2><%= link_to subeddit.name, subeddit_posts_path(subeddit)  %> </h2>
    <img style="max-width: 400px; height: auto" src=<%= subeddit.image %> ></img>
  </div>
<% end %>

app/views/subreddits/index.html.erb
<h1> Subreddits </h1>
<% @subreddits.each do |subreddit| %>
  <h2><%= link_to subreddit.title, subreddit_posts_url(subreddit) %> </h2>
  <img src=<%= subreddit.image %> style="height: 150px" />
<% end %>